BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            text: ''
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.3
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert miles to km'
    Label:
        text: ''
        color: (0, 1, 1, 1)